### PR TITLE
Add documentation

### PR DESCRIPTION
**Pull request by akshay-verma**
* Included short description and usage

### CODE REVIEW

**Comment by PrabhanshuAttri** [comment]
@akshay-verma Good work.
It seems that you have not configured git username and user email properly. The commit is not linked to your profile. Please update it using this [link](https://help.github.com/articles/setting-your-commit-email-address-in-git/) or you could just edit the author from [here](https://stackoverflow.com/questions/3042437/change-commit-author-at-one-specific-commit). 

Also, could you please add a screenshot. It's helpful in reviewing the PR. Thanks

**Comment by akshay-verma** [comment]
image

@PrabhanshuAttri I hope everything is configured correctly now. Attached the screenshot, its pretty basic!

**Comment by PrabhanshuAttri** [comment]
Thanks @akshay-verma Basic webpage works for now. Could you please use [Exo 2 font](https://fonts.google.com/specimen/Exo+2?selection.family=Exo+2) from google font?

**Comment by akshay-verma** [comment]
The long-term solution should be to use documentation generator Sphinx may be. Docstring must be maintained well to use that.

**Comment by PrabhanshuAttri** [comment]
Yes, I agree. I wanted a static site generator only, but a basic page is also a good start.

**Pull request merged**
