### PR TITLE
Add badges

### PR DESCRIPTION
**Pull request by mstuttgart**
- [x] Add Package Version badge. [PyPI](https://github.com/nirmankarta/PyBeacon)
- [x] Add License badge. [PyPI](https://github.com/nirmankarta/PyBeacon/blob/master/LICENSE)
- [x] Add flat style in badges:
[Travis branch](https://travis-ci.org/nirmankarta/PyBeacon)
[Python: 3](https://docs.python.org/3/)
[Python: 2](https://docs.python.org/2/)
[Slack](http://nirmankarta.herokuapp.com)

Update https://github.com/nirmankarta/PyBeacon/issues/26

### CODE REVIEW

**Comment by PrabhanshuAttri** [comment]
@mstuttgart Good work

Few changes:
1) Please create all PR against dev branch
2) We don't require all badges to be flat, so please revert the changes made to already present badges.
3) Add badges with the similar look.

Let me know if you need help.

**Comment by mstuttgart** [comment]
@PrabhanshuAttri please reopen this PR. I will rebase my commits and make this changes

**Comment by PrabhanshuAttri** [comment]
This PR is created against the master. I think you can't make it against dev branch

**Comment by mstuttgart** [comment]
- [x] Add Package Version badge. [PyPI](https://github.com/nirmankarta/PyBeacon)
- [x] Add License badge. [PyPI](https://github.com/nirmankarta/PyBeacon/blob/master/LICENSE)
- [x] My branch rebased with *dev* branch

@PrabhanshuAttri fixed

**Comment by PrabhanshuAttri** [comment]
@mstuttgart Good work.

**Pull request merged**
