### PR TITLE
Fix NameError

### PR DESCRIPTION
**Pull request by schedutron**

### CODE REVIEW

**Comment by schedutron** [comment]
Fixes #24.

**Comment by schedutron** [comment]
@PrabhanshuAttri I have changed the test definition to assert equality with the expected value itself. Is this okay?

**Comment by PrabhanshuAttri** [comment]
@schedutron There is something wrong here. It shows all the changes I have made and your changes as well. This can mess up the git history. Can you please create a PR with just your changes?

**Comment by PrabhanshuAttri** [comment]
@schedutron Could you please take pull from dev and fix these issues?

**Comment by schedutron** [comment]
@PrabhanshuAttri Everything all right now?

**Comment by PrabhanshuAttri** [comment]
I think so. What was the problem?

**Comment by schedutron** [comment]
@PrabhanshuAttri You asked to pull from dev and fix the history issues.

**Comment by PrabhanshuAttri** [comment]
Good work. Will merge it soon.

**Comment by schedutron** [comment]
@PrabhanshuAttri Thanks :)

**Comment by PrabhanshuAttri** [comment]
Could you please set ret on line 62 instead of directly asserting it in line 63?

**Comment by schedutron** [comment]
@PrabhanshuAttri Done.

**Pull request merged**
